name: wl
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/svg/
    - assets/fonts/
  fonts:
    - family: Polar
      fonts:
        - asset: assets/fonts/polar/ftp_polar_black.ttf
          weight: 900
        - asset: assets/fonts/polar/ftp_polar_black.ttf
          weight: 800
        - asset: assets/fonts/polar/ftp_polar_bold.ttf
          weight: 700
        - asset: assets/fonts/polar/ftp_polar_semibold.ttf
          weight: 600
        - asset: assets/fonts/polar/ftp_polar_medium.ttf
          weight: 500
        - asset: assets/fonts/polar/ftp_polar_regular.ttf
          weight: 400
        - asset: assets/fonts/polar/ftp_polar_thin.ttf
          weight: 300
        - asset: assets/fonts/polar/ftp_polar_light.ttf
          weight: 200
        - asset: assets/fonts/polar/ftp_polar_thin.ttf
          weight: 100
    - family: Kansas
      fonts:
        - asset: assets/fonts/kansas/kansasnew_black.ttf
          weight: 900
        - asset: assets/fonts/kansas/kansasnew_black.ttf
          weight: 800
        - asset: assets/fonts/kansas/kansasnew_bold.ttf
          weight: 700
        - asset: assets/fonts/kansas/kansasnew_semibold.ttf
          weight: 600
        - asset: assets/fonts/kansas/kansasnew_medium.ttf
          weight: 500
        - asset: assets/fonts/kansas/kansasnew_regular.ttf
          weight: 400
        - asset: assets/fonts/kansas/kansasnew_thin.ttf
          weight: 300
        - asset: assets/fonts/kansas/kansasnew_light.ttf
          weight: 200
        - asset: assets/fonts/kansas/kansasnew_thin.ttf
          weight: 100
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoe/segoe_ui_bold.ttf
          weight: 900
        - asset: assets/fonts/segoe/segoe_ui_bold.ttf
          weight: 800
        - asset: assets/fonts/segoe/segoe_ui_bold.ttf
          weight: 700
        - asset: assets/fonts/segoe/segoe_ui_bold.ttf
          weight: 600
        - asset: assets/fonts/segoe/segoe_ui_normal.ttf
          weight: 500
        - asset: assets/fonts/segoe/segoe_ui_normal.ttf
          weight: 400
        - asset: assets/fonts/segoe/segoe_ui_normal.ttf
          weight: 300
        - asset: assets/fonts/segoe/segoe_ui_normal.ttf
          weight: 200
        - asset: assets/fonts/segoe/segoe_ui_normal.ttf
          weight: 100
  uses-material-design: true
  generate: true
